# -*- coding: utf-8 -*-
"""1841720167_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/flight_delays.csv', index_col= 'Month')
df.info()
print(df.head())
print(df.tail())
print(df.isnull().sum())
print(df[df['US'].isnull()])