# -*- coding: utf-8 -*-
"""1841720167_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

from google.colab import drive
drive.mount('/content/drive')