# -*- coding: utf-8 -*-
"""1841720167_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/OnlineRetail.xlsx')
df.info()
print(df.isnull().any())
print(df.isnull().sum())
print(df[df['Description'].isnull()].head())