# -*- coding: utf-8 -*-
"""1841720167_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

nilai1 = 10
nilai2 = 20
nilai3 = 100
total = nilai1 + nilai2 \
  + nilai3
print(total)