# -*- coding: utf-8 -*-
"""1841720167_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

s = "SaMurai"
s.lower() #'samurai'
print(s)  #'saMurai'

s2 = s.lower()
print(s2) #'samurai'

name = input('What is your name? ')

print('Hi ' + name + '!')