# -*- coding: utf-8 -*-
"""1841720167_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

x = 100; y=150; z=22.56; hasil = x+2*y*z
print(hasil)