# -*- coding: utf-8 -*-
"""1841720167_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

#This is a comment
print ("Hello") # This is also a comment ass a code documentation