# -*- coding: utf-8 -*-
"""1841720167_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

myStr = 'Hello, Surabaya'
print(len(myStr))

pegawai = 'Sabine'
print("Nama : " , pegawai)
print("pass" + "word")

#age = 25
#myText = 'Age is'
#print(myText + age)  #error

age = 35
myText = ' Age is '
print(myText + str(age))

print("Python " * 3)