# -*- coding: utf-8 -*-
"""1841720167_15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

a = 10; b = 20
mylist = [1, 2, 3, 4, 5];

a=2
if (a in mylist):
  print ("Line 3 a is available in the given list")
else:
  print ("Line 3 a is not availalble in the given list")