# -*- coding: utf-8 -*-
"""1841720167_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

# 'Double' in Single
print('"Double" in single') #Hasil : "Double" in single

#"Double" in Double
print("\"Double\" in Double") #Hasil : "Double" in Double