# -*- coding: utf-8 -*-
"""1841720167_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

cabang = ['Jakarta', 'Bogor', 'Bandung', 'Solo', 'Malang', 'Surabaya',
          'Banyuwangi', 'Denpasar', 'Makassar']
print (cabang)