# -*- coding: utf-8 -*-
"""1841720167_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

x = None
print(type(x))    #output: NoneType

print(x == None)  #output: True
print(x)  #output: None