# -*- coding: utf-8 -*-
"""1841720167_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

counter = 100   #integer value assignment
jarak = 104.5   #floating point value
name = "nina"   #the name vatiable stores a string value

#multiple assignment in one command line :
a = b = c = 200
name, city, salary = "Sabine", 'Surabaya', 70000

print(counter)
print(jarak)
print(name)
print(a, b, c)
print(city)