# -*- coding: utf-8 -*-
"""1841720167_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16G85g500cVxEktOp0SpoXaaGZ8SE_9y7
"""

nama = 'Sabine'
kalimat = "This is a sentence."
paragraf = """This is a paragraph
Paragraph are made up of several line and sentences."""

print(nama)
print(kalimat)
print(paragraf)

print(nama[0:5])
print(nama[2:])
print(kalimat[-8:-1])