# -*- coding: utf-8 -*-
"""1841720167_1

Automatically generated by Colaboratory.

Original file is located at
    https://drive.google.com/drive/u/0/folders/1lmpZjHRwEjDbHL8rFKHFQugfDGms03ut
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Data Frame"""

## Import Dataset

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/Kampus/Semester 6/Teknologi Data/Minggu 5/BreadBasket_DMS.csv')

## Get Distinct/Unique Value

df.Item.unique()

len(df['Item'].unique())

## Displaying Unique Item by Removing Duplicates Data in a Column

df.Item.drop_duplicates()

#dataset overview

df.head(3)

## Display Unique Value and Its Total Count

topten = df.Item.value_counts()
topten.head(10)

## Missing Observation

topten = df.Item.value_counts()
topten.head(10)

## Drop Remove Row from Data Frame

df = df[df['Item'] != 'NONE']
df.info()

print("Number of unique item:", df.Item.nunique())
len(df['Item'].unique())

## Split String in DataFrame

df.head(3)

## Split String and Add New Column to Data Frame

df['Year'] = df['Date'].str[0:4]
df['Year'].head()

## Split String and Add New Column to Data Frame (2)

df['Year'] = df.Date.apply(lambda x: x.split('-')[0])
df['Month'] = df.Date.apply(lambda x: x.split('-')[1])
df['Day'] = df.Date.apply(lambda x: x.split('-')[2])
df['Hour'] = df.Time.apply(lambda x: int(x.split(':')[0]))
df.head()

## Review Top 10 Unique Items

item_sales = df.Item.value_counts()
topten = item_sales[:10]
topten

## Visualizing Using Chart

sns.set(style = 'whitegrid')
toptenbar = topten.plot.bar(title = 'Top 10 Sales')
toptenbar.legend(['Number of items sold'])

## Let's See Another Insight

coffeesales = df[df['Item'] == 'Coffee']
coffeesales.head(10)

## Other Coffee Transaction Information

coffeeTime = coffeesales['Hour'].value_counts()
coffeeTime = coffeesales['Hour'].value_counts().sort_index()
coffeeTime

## More Visualization

sns.set(style = 'whitegrid')
coffeetimebar = coffeeTime.plot.bar(title = 'Coffee Sales by Hour')
coffeetimebar.set_xlabel('Time of day')
coffeetimebar.set_ylabel('Number of coffee solid')
coffeetimebar.legend(['Number of coffee solid'])