# -*- coding: utf-8 -*-
"""1841720167_2

Automatically generated by Colaboratory.

Original file is located at
    https://drive.google.com/drive/u/0/folders/1lmpZjHRwEjDbHL8rFKHFQugfDGms03ut
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Weather"""

## Import Libraries and Dataset

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# %matplotlib inline

weather = pd.read_csv('/content/drive/MyDrive/Kampus/Semester 6/Teknologi Data/Minggu 5/BreadBasket_DMS.csv')
weather

## Simple Pandas Graph

weather.plot(y='Tmax', x='Month')
plt.show()

## Multiple Line Plots or Chart

weather.plot(y=['Tmax','Tmin'],x='Month')
plt.show()

## Bar Chart

weather.plot(kind='bar', y='Rain', x='Month')
plt.show()

## Horizontal Bar Chart

weather.plot(kind='barh', y='Rain', x='Month')
plt.show()

## Pie Chart

weather.plot(kind='pie', y='Sun')
plt.show()

## Scatterplot or Scatter diagram

weather.plot(kind='scatter', x='Sun', y='Rain')
plt.show()

## Multiple Plots or Chart

weather.plot(y=['Tmax', 'Tmin', 'Rain', 'Sun'], subplots=True, layout=(2,2), figsize=(10,5))
plt.show()

## Simply Saving Chart

weather.plot(kind='pie', y='Rain', legend=False)
plt.show()
plt.savefig('pie.png')